version: '3'
services:
  postgres_db:
    image: postgres:15
    container_name: posgresqltodocontainer
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - $PWD/_postgres_database:/var/lib/postgresql/data

volumes:
  postgres_database:
    driver: local
